# Generated by Django 6.0.4 on 2026-04-09 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content_blocks', models.JSONField(blank=True, default=list)),
                ('owner', models.CharField(max_length=100)),
                ('last_reviewed', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
