# Generated by Django 6.0.4 on 2026-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_blocks',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Use the editor below to format your document.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text="The URL name (e.g., 'office-security')", unique=True),
        ),
    ]
