# Generated by Django 6.0.4 on 2026-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_searchhistory_alter_article_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='admin_review_notes',
            field=models.TextField(blank=True, help_text='Notes from staff reviewing bad AI answers'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='is_queued',
            field=models.BooleanField(default=False, help_text='True if waiting for background AI generation'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='source_articles',
            field=models.ManyToManyField(blank=True, to='knowledge.article'),
        ),
    ]
